######################################################################
# Automatically generated by qmake (3.0) Thu Oct 23 04:56:55 2014
######################################################################

TEMPLATE = app
TARGET = test
INCLUDEPATH += .

# Input
CONFIG += qt debug
QT += widgets
HEADERS += mywidget.h
SOURCES += test.cpp mywidget.cpp
